/**
 * Helper function to create a srcset string from an array of image metadata objects.
 * Eg: [{src: "file-400.jpg", width: 400}] -> "file-400.jpg 400w"
 */
function createSrcset(imagesArray) {
    if (!imagesArray) return "";
    return imagesArray
        .map(img => `${img.src} ${img.width}w`)
        .join(", ");
}

/**
 * Defining a Custom Web Component: <smart-image>
 * This acts exactly like the React <Image /> component in Next.js.
 */
class SmartImage extends HTMLElement {
    
    // Automatically runs when the <smart-image> tag is added to the HTML DOM
    connectedCallback() {
        this.render();
    }

    async render() {
        // Read props (attributes) passed by the developer in HTML
        const srcAttr = this.getAttribute('src');
        const altText = this.getAttribute('alt') || '';
        const sizesAttr = this.getAttribute('sizes') || '100vw'; // Default to full width
        
        if (!srcAttr) {
            this.innerHTML = `<p style="color:orange; padding: 1rem;">Warning: No 'src' attribute provided to &lt;smart-image&gt;.</p>`;
            return;
        }

        try {
            // 1. Fetch the build manifest generated by Sharp
            const response = await fetch('./dist/image-manifest.json');
            
            if (!response.ok) {
                throw new Error("Manifest not found. Did you run `npm run build`?");
            }
            
            const manifest = await response.json();

            // 2. Extract metadata FOR THIS SPECIFIC IMAGE from the manifest
            const imageMetadata = manifest[srcAttr];

            if (!imageMetadata) {
                throw new Error(`Image metadata for "${srcAttr}" not found in manifest.`);
            }

            // 3. Generate the complex srcset strings for each format
            const avifSrcset = createSrcset(imageMetadata.avif);
            const webpSrcset = createSrcset(imageMetadata.webp);
            const jpegSrcset = createSrcset(imageMetadata.jpeg);

            // 4. We need a fallback `src` for the <img> tag inside <picture>.
            const fallbackSrc = imageMetadata.jpeg[Math.floor(imageMetadata.jpeg.length / 2)].src;

            // 5. Construct the beautiful, highly-optimized <picture> block!
            this.innerHTML = `
                <picture>
                    <source type="image/avif" srcset="${avifSrcset}" sizes="${sizesAttr}">
                    <source type="image/webp" srcset="${webpSrcset}" sizes="${sizesAttr}">
                    <img 
                        src="${fallbackSrc}" 
                        srcset="${jpegSrcset}" 
                        sizes="${sizesAttr}" 
                        alt="${altText}" 
                        loading="lazy"
                        decoding="async"
                    >
                </picture>
            `;

        } catch (error) {
            console.error("SmartImage Engine Error:", error);
            this.innerHTML = `<p style="color:red; padding: 1rem;">Failed to load image component. Please build images first.</p>`;
        }
    }
}

// Register our custom HTML tag with the browser!
customElements.define('smart-image', SmartImage);
